apiVersion: batch/v1
kind: CronJob
metadata:
name: mycron
spec:
schedule: "*/5 * * * *" # every 5 mins
jobTemplate:
spec:
template:
spec:
containers:
- name: mycron
image: busybox
command: ["echo", "Cron triggered!"]
restartPolicy: Never