apiVersion: apps/v1
kind: Deployment
metadata:
name: cm-app
spec:
replicas: 1
selector:
matchLabels:
app: cm-app
template:
metadata:
labels:
app: cm-app
spec:
containers:
- name: cm-app
image: nginx
envFrom:
- configMapRef:
name: app-config