# Persistent Volume + Persistent Volume Claim
apiVersion: apps/v1
kind: Deployment
metadata:
name: secret-app
spec:
replicas: 1
selector:
matchLabels:
app: secret-app
template:
metadata:
labels:
app: secret-app
spec:
containers:
- name: secret-app
image: nginx
env:
- name: DB_PASSWORD
valueFrom:
secretKeyRef:
name: app-secret
key: DB_PASSWORD