# . Rolling Update Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
name: rolling-app
spec:
replicas: 3
strategy:
type: RollingUpdate
rollingUpdate:
maxSurge: 1
maxUnavailable: 1
selector:
matchLabels:
app: rolling-app
template:
metadata:
labels:
app: rolling-app
spec:
containers:
- name: rolling-app
image: nginx:1.25