apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
name: devops-binding
subjects:
- kind: ServiceAccount
name: devops-sa
namespace: default
roleRef:
kind: ClusterRole
name: devops-role
apiGroup: rbac.authorization.k8s.io